'use client';

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

/**
 * @fileOverview Professional Emergency Procedure PDF Engine
 * Generates a branded safety notice for properties.
 * Hardcoded STEP 1 protocols for UK Law Compliance.
 */

export const generateEmergencyPDF = async (data: any, propertyAddress: string) => {
  if (!data) return null;

  const doc = new jsPDF();
  const pageHeight = doc.internal.pageSize.getHeight();
  let finalY = 0;

  // --- HEADER ---
  doc.setFillColor(239, 68, 68); // Red color for emergency
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setFontSize(24);
  doc.setTextColor(255);
  doc.text('EMERGENCY PROCEDURE', 105, 25, { align: 'center' });
  doc.setFontSize(10);
  doc.text('IMPORTANT SAFETY INFORMATION FOR RESIDENTS', 105, 33, { align: 'center' });

  finalY = 50;

  // --- PROPERTY CONTEXT ---
  doc.setTextColor(0);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Property Address:', 14, finalY);
  doc.setFont('helvetica', 'normal');
  doc.text(propertyAddress, 14, finalY + 7);
  finalY += 20;

  // --- STEP 1: IMMEDIATE DANGER ---
  doc.setFillColor(239, 68, 68);
  doc.rect(14, finalY, 182, 10, 'F');
  doc.setTextColor(255);
  doc.setFontSize(12);
  doc.text('STEP 1 – IMMEDIATE DANGER (ACT FIRST)', 105, finalY + 7, { align: 'center' });
  finalY += 15;

  doc.setTextColor(0);
  doc.setFontSize(10);
  const dangerLines = [
    ['Gas Leak', 'National Gas Emergency Service', '0800 111 999'],
    ['Electric Emergency', 'Call', '105'],
    ['Emergency Services', 'Fire / Police / Medical', '999']
  ];

  autoTable(doc, {
    startY: finalY,
    body: dangerLines,
    theme: 'grid',
    styles: { fontSize: 10, cellPadding: 5 },
    columnStyles: { 0: { fontStyle: 'bold' }, 2: { fontStyle: 'bold', textColor: [239, 68, 68] } }
  });

  finalY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFont('helvetica', 'bolditalic');
  doc.setTextColor(239, 68, 68);
  doc.text('Do NOT contact the landlord first in these situations.', 105, finalY, { align: 'center' });
  finalY += 15;

  // --- STEP 2: URGENT PROPERTY EMERGENCIES ---
  doc.setFillColor(249, 115, 22); // Orange
  doc.rect(14, finalY, 182, 10, 'F');
  doc.setTextColor(255);
  doc.text('STEP 2 – URGENT PROPERTY EMERGENCIES (24/7)', 105, finalY + 7, { align: 'center' });
  finalY += 15;

  doc.setTextColor(0);
  doc.setFont('helvetica', 'bold');
  doc.text('Emergency Repair Contact:', 14, finalY);
  doc.setFont('helvetica', 'normal');
  
  // Handled with maxWidth to ensure long names wrap instead of overlapping
  const contactName = data.emergencyRepairContact || 'Property Support';
  const splitContact = doc.splitTextToSize(contactName, 120);
  doc.text(splitContact, 75, finalY);
  
  finalY += (splitContact.length * 5) + 2;
  
  doc.setFont('helvetica', 'bold');
  doc.text('Emergency Phone:', 14, finalY);
  doc.setFont('helvetica', 'normal');
  doc.text(data.emergencyRepairPhone || 'N/A', 75, finalY);
  finalY += 10;

  doc.setFontSize(9);
  doc.text('Examples: Burst pipes / major water leaks, total loss of electricity (internal issue), no heating or hot water (winter), broken security.', 14, finalY, { maxWidth: 180 });
  finalY += 15;

  // --- NON-EMERGENCY REPAIRS ---
  doc.setFillColor(34, 197, 94); // Green
  doc.rect(14, finalY, 182, 10, 'F');
  doc.setTextColor(255);
  doc.text('NON-EMERGENCY REPAIRS (WORKING HOURS)', 105, finalY + 7, { align: 'center' });
  finalY += 15;

  doc.setTextColor(0);
  doc.setFont('helvetica', 'bold');
  doc.text('Contact Phone Number:', 14, finalY);
  doc.setFont('helvetica', 'normal');
  doc.text(data.nonEmergencyPhone || 'N/A', 75, finalY);
  finalY += 7;
  doc.setFont('helvetica', 'bold');
  doc.text('Contact Email:', 14, finalY);
  doc.setFont('helvetica', 'normal');
  doc.text(data.nonEmergencyEmail || 'N/A', 75, finalY);
  finalY += 15;

  // --- MANAGEMENT DETAILS ---
  doc.setDrawColor(200);
  doc.line(14, finalY, 196, finalY);
  finalY += 10;
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Landlord / Agent Identity:', 14, finalY);
  finalY += 7;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Name: ${data.landlordName || 'N/A'}`, 14, finalY);
  finalY += 5;
  doc.text(`Email: ${data.landlordEmail || 'N/A'}`, 14, finalY);
  finalY += 5;
  doc.text(`Correspondence: ${data.landlordAddress || 'Refer to registry'}`, 14, finalY, { maxWidth: 180 });

  // --- FOOTER ---
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(`Official Safety Notice Generated by RentSafeUK on ${format(new Date(), 'PPpp')}`, 105, 285, { align: 'center' });

  doc.save(`Emergency-Procedure-${propertyAddress.replace(/[^\w\s-]/g, '').replace(/\s+/g, '-')}.pdf`);
  return doc;
};
